version: "3.8"
services:
  frontend:
    build:
      context: "./frontend"
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    image: hmohammed2/geocode-api-frontend:v1.0.0
    env_file:
      - ./frontend/.env.production

  geocode_api:
    build:
      context: "./backend-api"
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    image: hmohammed2/geocode-api:v1.0.0
    env_file:
      - ./backend-api/.env.production
    environment:
      - NODE_ENV=production